### ISSUE TITLE
Issue with Deploy the Connectivity Infrastructure

### ISSUE THREAD

**Issue by Darthick** [FreddyAyala/AzureAIServicesLandingZone#2]
Hi,
 I am getting the below error while executing the Deploy the Connectivity Infrastructure step.

│ Error: Invalid value for input variable
│ 
│   on connectivity/main.tf line 45, in module "enterprise_scale":
│   45:   configure_connectivity_resources = var.configure_connectivity_resources
│ 
│ The given value is not suitable for module.connectivity.module.enterprise_scale.var.configure_connectivity_resources declared at .terraform/modules/connectivity.enterprise_scale/variables.tf:156,1-44: attribute "settings":
│ attribute "hub_networks": element 0: attribute "config": attribute "spoke_virtual_network_resource_ids": list of string required.

Please advise.

Many Thanks,
Darthick S

**Comment by FreddyAyala** [comment]
Could you please share the value of the variable in your terraform.tfvars spoke_peerings??

The problem comes from this line:  spoke_virtual_network_resource_ids      = var.spoke_peerings

**Comment by Darthick** [comment]
Hi,
Please find below the requested snippet.

spoke_peerigns =["/subscriptions/[Actual SubscriptionsID]/resourceGroups/rg-network/providers/Microsoft.Network/virtualNetworks/vnet-ai-lz"] #Update this after deploying Spoke and then redeploy LZ

Thanks,
Darthick S

**Comment by Darthick** [comment]
Hi Freddy,
I found the root cause for this issue. There is a typo in "spoke_peerigns" . I changed it to **spoke_peerings** . Now that issue is resolved. But I am getting another issue. 

│ Error: Invalid for_each argument
│ 
│   on ../Modules/Core/DNS/private-dns-vnet-link/main.tf line 17, in resource "azurerm_private_dns_zone_virtual_network_link" "vnet_links":
│   17:  for_each = { for association in local.vnet_zone_associations : "${replace(replace(replace(substr("${replace(replace(association.zone_name, ".", "-"), "/", "-")}-${split("/", association.vnet_id)[8]}", 0, 80), "azure", "az"), "privatelink", "pvtlk"), "shared services", "shrsvc")}" => association }
│     ├────────────────
│     │ local.vnet_zone_associations is tuple with 2 elements
│ 
│ The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify the instances of this resource.
│ 
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and place apply-time results only in the map values.
│ 
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and then apply a second time to fully converge.
╵
Thanks,
Darthick S

**Comment by FreddyAyala** [comment]
I've pushed some, please try in the file connectivity.dns.privatelink.tf module "private_dns_link" {
  source              = "../Modules/Core/DNS/private-dns-vnet-link"
  resource_group_name = module.connectivity.dns_resource_group_name
  vnets_to_associate  = [values(values(module.connectivity.module.azurerm_virtual_network)[0])[0].id]
  json_policies_file  = "${path.module}/private-zones.json"

  providers = {
    azurerm = "azurerm.connectivity"
  }
depends_on = [module.connectivity  ]
}

**Comment by Darthick** [comment]
No luck :(  still with the same error.

Error: Invalid for_each argument
│ 
│   on ../Modules/Core/DNS/private-dns-vnet-link/main.tf line 17, in resource "azurerm_private_dns_zone_virtual_network_link" "vnet_links":
│   17:  for_each = { for association in local.vnet_zone_associations : "${replace(replace(replace(substr("${replace(replace(association.zone_name, ".", "-"), "/", "-")}-${split("/", association.vnet_id)[8]}", 0, 80), "azure", "az"), "privatelink", "pvtlk"), "shared services", "shrsvc")}" => association }
│     ├────────────────
│     │ local.vnet_zone_associations is tuple with 2 elements
│ 
│ The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify the instances of this resource.
│ 
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and place apply-time results only in the map values.
│ 
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and then apply a second time to fully converge.
╵

**Comment by FreddyAyala** [comment]
Don't worry, for the moment comment this part of the code: module "private_dns_link" {
  source              = "../Modules/Core/DNS/private-dns-vnet-link"
  resource_group_name = module.connectivity.dns_resource_group_name
  vnets_to_associate  = [values(values(module.connectivity.module.azurerm_virtual_network)[0])[0].id]
  json_policies_file  = "${path.module}/private-zones.json"

  providers = {
    azurerm = "azurerm.connectivity"
  }
depends_on = [module.connectivity  ]
}

and then deploy, then we can uncomment it to surpass this blocker, then I will try to find a more permanent workaround

**Comment by Darthick** [comment]
Hi Freddy,
Thanks for the input. I have commented the snippet and executer the plan. It completed successfully. But, when deploying , it failed with the below error.

│ Error: waiting for Virtual Network Peering: (Name "peering-ad1f8d4c-2369-5463-923e-6edb9dee9788" / Virtual Network Name "es-hub-eastus" / Resource Group "es-connectivity-eastus") to be created: network.VirtualNetworkPeeringsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidGlobalResourceReference" Message="Resource /subscriptions/subid/resourceGroups/rg-network/providers/Microsoft.Network/virtualNetworks/vnet-ai-lz referenced by resource /subscriptions/<Subid>/resourceGroups/es-connectivity-eastus/providers/Microsoft.Network/virtualNetworks/es-hub-eastus/virtualNetworkPeerings/peering-ad1f8d4c-2369-5463-923e-6edb9dee9788 was not found. Please make sure that the referenced resource exists." Details=[]
│ 
│   with module.connectivity.module.enterprise_scale.azurerm_virtual_network_peering.connectivity["/subscriptions/subid/resourceGroups/es-connectivity-eastus/providers/Microsoft.Network/virtualNetworks/es-hub-eastus/virtualNetworkPeerings/peering-ad1f8d4c-2369-5463-923e-6edb9dee9788"],
│   on .terraform/modules/connectivity.enterprise_scale/resources.connectivity.tf line 530, in resource "azurerm_virtual_network_peering" "connectivity":
│  530: resource "azurerm_virtual_network_peering" "connectivity" {

**Comment by Darthick** [comment]
Hi Freddy,
I created the missed out Vnet manually and proceeded further. Now am getting errors in the policies.
Can you please help here?

╷
│ Error: creating Solution (Subscription: "<subid>"
│ Resource Group Name: "es-mgmt"
│ Solution Name: "VMInsights(es-la)"): performing CreateOrUpdate: unexpected status 403 with error: RequestDisallowedByPolicy: Resource 'VMInsights(es-la)' was disallowed by policy. Reasons: 'Resources must only be deployed to the allowed locations.'. See error details for policy resource IDs.
│ 
│   with module.management.module.enterprise_scale_management.azurerm_log_analytics_solution.management["/subscriptions/<subid>/resourceGroups/es-mgmt/providers/Microsoft.OperationsManagement/solutions/VMInsights(es-la)"],
│   on .terraform/modules/management.enterprise_scale_management/resources.management.tf line 41, in resource "azurerm_log_analytics_solution" "management":
│   41: resource "azurerm_log_analytics_solution" "management" {
│ 
│ creating Solution (Subscription: "<subid>"
│ Resource Group Name: "es-mgmt"
│ Solution Name: "VMInsights(es-la)"): performing CreateOrUpdate: unexpected status 403 with error: RequestDisallowedByPolicy: Resource 'VMInsights(es-la)' was disallowed by policy. Reasons: 'Resources must only be deployed to
│ the allowed locations.'. See error details for policy resource IDs.
╵
╷
│ Error: creating Solution (Subscription: "<subid>"
│ Resource Group Name: "es-mgmt"
│ Solution Name: "Updates(es-la)"): performing CreateOrUpdate: unexpected status 403 with error: RequestDisallowedByPolicy: Resource 'Updates(es-la)' was disallowed by policy. Reasons: 'Resources must only be deployed to the allowed locations.'. See error details for policy resource IDs.
│ 
│   with module.management.module.enterprise_scale_management.azurerm_log_analytics_solution.management["/subscriptions/<subid>/resourceGroups/es-mgmt/providers/Microsoft.OperationsManagement/solutions/Updates(es-la)"],
│   on .terraform/modules/management.enterprise_scale_management/resources.management.tf line 41, in resource "azurerm_log_analytics_solution" "management":
│   41: resource "azurerm_log_analytics_solution" "management" {
│ 
│ creating Solution (Subscription: "<subid>"
│ Resource Group Name: "es-mgmt"
│ Solution Name: "Updates(es-la)"): performing CreateOrUpdate: unexpected status 403 with error: RequestDisallowedByPolicy: Resource 'Updates(es-la)' was disallowed by policy. Reasons: 'Resources must only be deployed to the
│ allowed locations.'. See error details for policy resource IDs.
╵
╷
│ Error: creating Network Interface (Subscription: "<subid>"
│ Resource Group Name: "es-connectivity-westeurope"
│ Network Interface Name: "nic-vmlzvmjumpserv"): performing CreateOrUpdate: unexpected status 403 with error: RequestDisallowedByPolicy: Resource 'nic-vmlzvmjumpserv' was disallowed by policy. Reasons: 'Resources must only be deployed to the allowed locations.'. See error details for policy resource IDs.
│ 
│   with module.connectivity.module.virtual-machine.azurerm_network_interface.nic[0],
│   on ../Modules/Core/virtual-machine/main.tf line 88, in resource "azurerm_network_interface" "nic":
│   88: resource "azurerm_network_interface" "nic" {
│ 
╵
╷
│ Error: creating Inbound Endpoint (Subscription: "<subid>"
│ Resource Group Name: "es-connectivity-westeurope"
│ Dns Resolver Name: "dns-priv-resolver"
│ Inbound Endpoint Name: "inboundsubnetdns"): performing CreateOrUpdate: unexpected status 403 with error: RequestDisallowedByPolicy: Resource 'inboundsubnetdns' was disallowed by policy. Reasons: 'Resources must only be deployed to the allowed locations.'. See error details for policy resource IDs.
│ 
│   with module.connectivity.module.private_dns_resolver.azurerm_private_dns_resolver_inbound_endpoint.private_dns_resolver_inbound_endpoint,
│   on ../Modules/Core/DNS/private_dns_resolver/main.tf line 9, in resource "azurerm_private_dns_resolver_inbound_endpoint" "private_dns_resolver_inbound_endpoint":
│    9: resource "azurerm_private_dns_resolver_inbound_endpoint" "private_dns_resolver_inbound_endpoint" {
│ 
│ creating Inbound Endpoint (Subscription: "<subid>"
│ Resource Group Name: "es-connectivity-westeurope"
│ Dns Resolver Name: "dns-priv-resolver"
│ Inbound Endpoint Name: "inboundsubnetdns"): performing CreateOrUpdate: unexpected status 403 with error: RequestDisallowedByPolicy: Resource 'inboundsubnetdns' was disallowed by policy. Reasons: 'Resources must only be deployed
│ to the allowed locations.'. See error details for policy resource IDs.
╵
╷
│ Error: creating Outbound Endpoint (Subscription: "<subid>"
│ Resource Group Name: "es-connectivity-westeurope"
│ Dns Resolver Name: "dns-priv-resolver"
│ Outbound Endpoint Name: "outboundsubnetdns"): performing CreateOrUpdate: unexpected status 403 with error: RequestDisallowedByPolicy: Resource 'outboundsubnetdns' was disallowed by policy. Reasons: 'Resources must only be deployed to the allowed locations.'. See error details for policy resource IDs.
│ 
│   with module.connectivity.module.private_dns_resolver.azurerm_private_dns_resolver_outbound_endpoint.private_dns_resolver_outbound_endpoint,
│   on ../Modules/Core/DNS/private_dns_resolver/main.tf line 23, in resource "azurerm_private_dns_resolver_outbound_endpoint" "private_dns_resolver_outbound_endpoint":
│   23: resource "azurerm_private_dns_resolver_outbound_endpoint" "private_dns_resolver_outbound_endpoint" {
│ 
│ creating Outbound Endpoint (Subscription: "<subid>"
│ Resource Group Name: "es-connectivity-westeurope"
│ Dns Resolver Name: "dns-priv-resolver"
│ Outbound Endpoint Name: "outboundsubnetdns"): performing CreateOrUpdate: unexpected status 403 with error: RequestDisallowedByPolicy: Resource 'outboundsubnetdns' was disallowed by policy. Reasons: 'Resources must only be
│ deployed to the allowed locations.'. See error details for policy resource IDs.


Thanks,
Darthick S

**Comment by FreddyAyala** [comment]
Hello thanks for the feedback, I've deployed again from zero and made several corrections, can you try again please?

**Comment by Darthick** [comment]
Hi Freddy,
Thank you for the updated files. Now I am getting the below error. I manually deleted the file and try to run the scripts but it fails with the same error again.


│ Error: A resource with the ID "/subscriptions/<subid>/resourceGroups/es-dns/providers/Microsoft.Network/privateDnsZones/privatelink.cognitiveservices.azure.com" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_private_dns_zone" for more information.
│ 
│   with module.private_link_dns_integration.azurerm_private_dns_zone.private_dns_zones["privatelink.cognitiveservices.azure.com"],
│   on ../Modules/Core/DNS/azure-private-endpoint-dns-integration/deploy-private-dns-zones.tf line 22, in resource "azurerm_private_dns_zone" "private_dns_zones":
│   22: resource "azurerm_private_dns_zone" "private_dns_zones" {

**Comment by FreddyAyala** [comment]
Yes it's a failure in the deployment, manually delete that resource and deploy again

**Comment by Darthick** [comment]
Yeah, am doing that. So each time the deployment fails, I am cleaning up all the resources that were deployed earlier before I redeploy it. Now I am getting the below error :(



Error: polling after CreateOrUpdate: executing request: unexpected status 404 received with no body
│ 
│   with module.management.module.enterprise_scale_management.azurerm_log_analytics_workspace.management["/subscriptions/<>/resourceGroups/es-mgmt/providers/Microsoft.OperationalInsights/workspaces/es-la"],
│   on .terraform/modules/management.enterprise_scale_management/resources.management.tf line 12, in resource "azurerm_log_analytics_workspace" "management":
│   12: resource "azurerm_log_analytics_workspace" "management" {

**Comment by FreddyAyala** [comment]
Hello, I've just redeplyoed everything and seems to be working correctly, so maybe you might need to to a terraform destroy and restart the deployment. On the otherhand could you tell me which region you are deploying to? there are some limitations in a few regions that might make bugs to appear. thanks for the patiente.

**Comment by Darthick** [comment]
Hello Freddy,
Thank you for the updates. Initially i tried to deploy it in the West Europe and later I am deploying using eastus

**Comment by FreddyAyala** [comment]
Yes i think you might need to start a new, make a terraform destroy, and then start from zero, also take notice of this: VERY IMPORTANT: In the file settings.connectivity.tf Near line 196 you need to change this parameter to match your target region:
advanced = {
      custom_settings_by_resource_type = {
        azurerm_subnet = {
          connectivity = {
            canadaeast = {             # <=== UPDATE THIS replace with the location you are using
              inboundsubnetdns = {

Furthermore make sure you are using the lastest terraform version.

**Comment by Darthick** [comment]
Hi Freddy,

I have 
---- upgraded the terraform to latest version
---- destroyed the terraform plan and apply.
---- removed all the resources and resource groups associated to that subscription. After running for long time, I received the below errors. 



│ Error: A resource with the ID "/subscriptions/<<subid>>/resourceGroups/es-connectivity-eastus/providers/Microsoft.Network/azureFirewalls/es-fw-eastus|hub-vnet-fw-diagnostic-settings" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_monitor_diagnostic_setting" for more information.
│ 
│   with module.connectivity.azurerm_monitor_diagnostic_setting.main,
│   on connectivity/main.tf line 60, in resource "azurerm_monitor_diagnostic_setting" "main":
│   60: resource "azurerm_monitor_diagnostic_setting" "main" {
│ 
╵
╷
│ Error: A resource with the ID "/providers/Microsoft.Management/managementGroups/contoso-landing-zones/providers/Microsoft.Authorization/policyAssignments/Deploy-SQL-Threat" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_management_group_policy_assignment" for more information.
│ 
│   with module.core.module.enterprise_scale_core.azurerm_management_group_policy_assignment.enterprise_scale["/providers/Microsoft.Management/managementGroups/contoso-landing-zones/providers/Microsoft.Authorization/policyAssignments/Deploy-SQL-Threat"],
│   on .terraform/modules/core.enterprise_scale_core/resources.policy_assignments.tf line 1, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│    1: resource "azurerm_management_group_policy_assignment" "enterprise_scale" {
│ 
│ A resource with the ID "/providers/Microsoft.Management/managementGroups/contoso-landing-zones/providers/Microsoft.Authorization/policyAssignments/Deploy-SQL-Threat" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for
│ "azurerm_management_group_policy_assignment" for more information.
╵
╷
│ Error: A resource with the ID "/providers/Microsoft.Management/managementGroups/contoso/providers/Microsoft.Authorization/policyAssignments/Deploy-MDFC-Config" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_management_group_policy_assignment" for more information.
│ 
│   with module.core.module.enterprise_scale_core.azurerm_management_group_policy_assignment.enterprise_scale["/providers/Microsoft.Management/managementGroups/contoso/providers/Microsoft.Authorization/policyAssignments/Deploy-MDFC-Config"],
│   on .terraform/modules/core.enterprise_scale_core/resources.policy_assignments.tf line 1, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│    1: resource "azurerm_management_group_policy_assignment" "enterprise_scale" {
│ 
│ A resource with the ID "/providers/Microsoft.Management/managementGroups/contoso/providers/Microsoft.Authorization/policyAssignments/Deploy-MDFC-Config" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for
│ "azurerm_management_group_policy_assignment" for more information.
╵
╷
│ Error: A resource with the ID "/providers/Microsoft.Management/managementGroups/contoso-management/providers/Microsoft.Authorization/policyAssignments/Deploy-Log-Analytics" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_management_group_policy_assignment" for more information.
│ 
│   with module.core.module.enterprise_scale_core.azurerm_management_group_policy_assignment.enterprise_scale["/providers/Microsoft.Management/managementGroups/contoso-management/providers/Microsoft.Authorization/policyAssignments/Deploy-Log-Analytics"],
│   on .terraform/modules/core.enterprise_scale_core/resources.policy_assignments.tf line 1, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│    1: resource "azurerm_management_group_policy_assignment" "enterprise_scale" {
│ 
│ A resource with the ID "/providers/Microsoft.Management/managementGroups/contoso-management/providers/Microsoft.Authorization/policyAssignments/Deploy-Log-Analytics" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for
│ "azurerm_management_group_policy_assignment" for more information.
╵
╷
│ Error: A resource with the ID "/providers/Microsoft.Management/managementGroups/contoso-sandboxes/providers/Microsoft.Authorization/policyAssignments/Enforce-ALZ-Sandbox" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_management_group_policy_assignment" for more information.
│ 
│   with module.core.module.enterprise_scale_core.azurerm_management_group_policy_assignment.enterprise_scale["/providers/Microsoft.Management/managementGroups/contoso-sandboxes/providers/Microsoft.Authorization/policyAssignments/Enforce-ALZ-Sandbox"],
│   on .terraform/modules/core.enterprise_scale_core/resources.policy_assignments.tf line 1, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│    1: resource "azurerm_management_group_policy_assignment" "enterprise_scale" {
│ 
│ A resource with the ID "/providers/Microsoft.Management/managementGroups/contoso-sandboxes/providers/Microsoft.Authorization/policyAssignments/Enforce-ALZ-Sandbox" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for
│ "azurerm_management_group_policy_assignment" for more information.
╵
╷
│ Error: A resource with the ID "/providers/Microsoft.Management/managementGroups/contoso/providers/Microsoft.Authorization/policyAssignments/Enforce-ACSB" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_management_group_policy_assignment" for more information.
│ 
│   with module.core.module.enterprise_scale_core.azurerm_management_group_policy_assignment.enterprise_scale["/providers/Microsoft.Management/managementGroups/contoso/providers/Microsoft.Authorization/policyAssignments/Enforce-ACSB"],
│   on .terraform/modules/core.enterprise_scale_core/resources.policy_assignments.tf line 1, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│    1: resource "azurerm_management_group_policy_assignment" "enterprise_scale" {
│ 
│ A resource with the ID "/providers/Microsoft.Management/managementGroups/contoso/providers/Microsoft.Authorization/policyAssignments/Enforce-ACSB" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for
│ "azurerm_management_group_policy_assignment" for more information.
╵
╷
│ Error: A resource with the ID "/providers/Microsoft.Management/managementGroups/contoso/providers/Microsoft.Authorization/policyAssignments/Deploy-ASC-Monitoring" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_management_group_policy_assignment" for more information.
│ 
│   with module.core.module.enterprise_scale_core.azurerm_management_group_policy_assignment.enterprise_scale["/providers/Microsoft.Management/managementGroups/contoso/providers/Microsoft.Authorization/policyAssignments/Deploy-ASC-Monitoring"],
│   on .terraform/modules/core.enterprise_scale_core/resources.policy_assignments.tf line 1, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│    1: resource "azurerm_management_group_policy_assignment" "enterprise_scale" {
│ 
│ A resource with the ID "/providers/Microsoft.Management/managementGroups/contoso/providers/Microsoft.Authorization/policyAssignments/Deploy-ASC-Monitoring" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for
│ "azurerm_management_group_policy_assignment" for more information.
╵
╷
│ Error: A resource with the ID "/providers/Microsoft.Management/managementGroups/contoso-landing-zones/providers/Microsoft.Authorization/policyAssignments/Deploy-VM-Backup" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_management_group_policy_assignment" for more information.
│ 
│   with module.core.module.enterprise_scale_core.azurerm_management_group_policy_assignment.enterprise_scale["/providers/Microsoft.Management/managementGroups/contoso-landing-zones/providers/Microsoft.Authorization/policyAssignments/Deploy-VM-Backup"],
│   on .terraform/modules/core.enterprise_scale_core/resources.policy_assignments.tf line 1, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│    1: resource "azurerm_management_group_policy_assignment" "enterprise_scale" {
│ 
│ A resource with the ID "/providers/Microsoft.Management/managementGroups/contoso-landing-zones/providers/Microsoft.Authorization/policyAssignments/Deploy-VM-Backup" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for
│ "azurerm_management_group_policy_assignment" for more information.
╵
╷
│ Error: A resource with the ID "/providers/Microsoft.Management/managementGroups/contoso/providers/Microsoft.Authorization/policyAssignments/Deploy-MDEndpoints" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_management_group_policy_assignment" for more information.
│ 
│   with module.core.module.enterprise_scale_core.azurerm_management_group_policy_assignment.enterprise_scale["/providers/Microsoft.Management/managementGroups/contoso/providers/Microsoft.Authorization/policyAssignments/Deploy-MDEndpoints"],
│   on .terraform/modules/core.enterprise_scale_core/resources.policy_assignments.tf line 1, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│    1: resource "azurerm_management_group_policy_assignment" "enterprise_scale" {
│ 
│ A resource with the ID "/providers/Microsoft.Management/managementGroups/contoso/providers/Microsoft.Authorization/policyAssignments/Deploy-MDEndpoints" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for
│ "azurerm_management_group_policy_assignment" for more information.
╵
╷
│ Error: A resource with the ID "/providers/Microsoft.Management/managementGroups/contoso-landing-zones/providers/Microsoft.Authorization/policyAssignments/Deny-IP-forwarding" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_management_group_policy_assignment" for more information.
│ 
│   with module.core.module.enterprise_scale_core.azurerm_management_group_policy_assignment.enterprise_scale["/providers/Microsoft.Management/managementGroups/contoso-landing-zones/providers/Microsoft.Authorization/policyAssignments/Deny-IP-forwarding"],
│   on .terraform/modules/core.enterprise_scale_core/resources.policy_assignments.tf line 1, in resource "azurerm_management_group_policy_assignment" "enterprise_scale":
│    1: resource "azurerm_management_group_policy_assignment" "enterprise_scale" {
│ 
│ A resource with the ID "/providers/Microsoft.Management/managementGroups/contoso-landing-zones/providers/Microsoft.Authorization/policyAssignments/Deny-IP-forwarding" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for
│ "azurerm_management_group_policy_assignment" for more information.

**Comment by Darthick** [comment]
Hi Freddy,
I am able to deploy the Landing zone successfully in our environment. Thanks a lot for your updates. 
One observation:
The code is looking for the a vnet resource **vnet-ai-lz** under resource Group : **rg-network**.The code is not creating this particular RG and Resource. So, I manually created the same and executed the scripts. After that it was successfully deployed.
Please take this into consideration in the future.

Thanks again!

Regards,
Darthick S

**Comment by FreddyAyala** [comment]
Thank you very much for the patience and very glad you could deploy it :) I will do a redeployment and validate the resource group problem later on.

**Comment by radhey-0603** [comment]
Hi [Darthick]/FreddyAyala,

What subnet address space you have defined there for vnet-ai-lz  ?
